version: "3"
tasks:
  lint:
    deps:
      - task: :gha-lint
      - task: :hadolint
  gha-lint:
    vars:
      PINACT_VERSION: v3.4.4
      ACTIONLINT_VERSION: v1.7.8
      GHALINT_VERSION: v1.5.3
    cmds:
      - go run github.com/suzuki-shunsuke/pinact/v3/cmd/pinact@{{.PINACT_VERSION}} run
      - go run github.com/rhysd/actionlint/cmd/actionlint@{{.ACTIONLINT_VERSION}}
      - go run github.com/suzuki-shunsuke/ghalint/cmd/ghalint@{{.GHALINT_VERSION}} run
  hadolint:
    cmds:
      - docker run --rm -i -v {{.TASK_DIR}}/.hadolint.yml:/.config/hadolint.yaml ghcr.io/hadolint/hadolint < amd64.dockerfile
      - docker run --rm -i -v {{.TASK_DIR}}/.hadolint.yml:/.config/hadolint.yaml ghcr.io/hadolint/hadolint < arm64.dockerfile
  format:
    vars:
      YAMLFMT_VERSION: v0.20.0
    cmds:
      - go run github.com/google/yamlfmt/cmd/yamlfmt@{{.YAMLFMT_VERSION}}
